"""Revisão das tabelas de  professor

Revision ID: 00dc78ac70bb
Revises: d0d5ae17abe0
Create Date: 2025-10-16 12:01:48.768771

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '00dc78ac70bb'
down_revision: Union[str, None] = 'd0d5ae17abe0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dados_dos_alunos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('telefone', sa.String(length=20), nullable=True),
    sa.Column('restricoes', sa.Text(), nullable=True),
    sa.Column('interesses', sa.Text(), nullable=True),
    sa.Column('evolucao', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dados_dos_alunos_id'), 'dados_dos_alunos', ['id'], unique=False)
    op.create_table('professores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('senha', sa.String(length=100), nullable=False),
    sa.Column('identificador', sa.String(length=100), nullable=True),
    sa.Column('tipo_identificador', sa.Enum('cpf', 'rg', 'outro', name='tipoidentificador'), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_professores_id'), 'professores', ['id'], unique=False)
    op.create_table('agendas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('professor_id', sa.Integer(), nullable=False),
    sa.Column('data_hora', sa.DateTime(), nullable=False),
    sa.Column('tipo_aula', sa.String(length=50), nullable=True),
    sa.Column('estudo', sa.String(length=100), nullable=True),
    sa.Column('alunos_confirmados', sa.Integer(), nullable=True),
    sa.Column('max_alunos', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('disponivel', 'em_andamento', 'finalizada', name='statusaula'), nullable=True),
    sa.ForeignKeyConstraint(['professor_id'], ['professores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agendas_id'), 'agendas', ['id'], unique=False)
    op.create_table('alunos_na_aula',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('agenda_id', sa.Integer(), nullable=False),
    sa.Column('aluno_nome', sa.String(length=100), nullable=True),
    sa.Column('presenca', sa.Enum('presente', 'ausente', 'indefinido', name='presenca'), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['agenda_id'], ['agendas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alunos_na_aula_id'), 'alunos_na_aula', ['id'], unique=False)
    op.drop_index('email', table_name='minha_conta')
    op.drop_index('ix_Minha_Conta_oid', table_name='minha_conta')
    op.drop_table('minha_conta')
    op.drop_index('ix_Minha_Agenda_id', table_name='minha_agenda')
    op.drop_table('minha_agenda')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('minha_agenda',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('data_hora', mysql.DATETIME(), nullable=False),
    sa.Column('tipo_aula', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('estudo', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('alunos_confirmados', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('max_alunos', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('status', mysql.ENUM('disponivel', 'em_andamento', 'finalizada'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_Minha_Agenda_id', 'minha_agenda', ['id'], unique=False)
    op.create_table('minha_conta',
    sa.Column('oid', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nome', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('telefone', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('email', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('status_pagamento', mysql.ENUM('pendente', 'pago', 'atrasado'), nullable=True),
    sa.PrimaryKeyConstraint('oid'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_Minha_Conta_oid', 'minha_conta', ['oid'], unique=False)
    op.create_index('email', 'minha_conta', ['email'], unique=True)
    op.drop_index(op.f('ix_alunos_na_aula_id'), table_name='alunos_na_aula')
    op.drop_table('alunos_na_aula')
    op.drop_index(op.f('ix_agendas_id'), table_name='agendas')
    op.drop_table('agendas')
    op.drop_index(op.f('ix_professores_id'), table_name='professores')
    op.drop_table('professores')
    op.drop_index(op.f('ix_dados_dos_alunos_id'), table_name='dados_dos_alunos')
    op.drop_table('dados_dos_alunos')
    # ### end Alembic commands ###
