"""teste de versoes

Revision ID: 5df0a64b9c8f
Revises: cce161bb4897
Create Date: 2025-10-10 21:57:12.693764

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '5df0a64b9c8f'
down_revision: Union[str, None] = 'cce161bb4897'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Agendamentos',
    sa.Column('oid', sa.Integer(), nullable=False),
    sa.Column('data_hora', sa.DateTime(), nullable=False),
    sa.Column('professor', sa.String(length=100), nullable=True),
    sa.Column('aula', sa.String(length=50), nullable=True),
    sa.Column('minha_presenca', sa.Enum('presente', 'ausente', 'indefinido', name='presenca'), nullable=True),
    sa.PrimaryKeyConstraint('oid')
    )
    op.create_index(op.f('ix_Agendamentos_oid'), 'Agendamentos', ['oid'], unique=False)
    op.create_table('Alunos_na_Aula',
    sa.Column('agendamento_id', sa.Integer(), nullable=False),
    sa.Column('aula_id', sa.Integer(), nullable=False),
    sa.Column('aluno_nome', sa.String(length=100), nullable=True),
    sa.Column('presenca', sa.Enum('presente', 'ausente', 'indefinido', name='presenca'), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('agendamento_id', 'aula_id')
    )
    op.create_table('Aulas_Disponiveis',
    sa.Column('oid', sa.Integer(), nullable=False),
    sa.Column('data_hora', sa.DateTime(), nullable=False),
    sa.Column('professor', sa.String(length=100), nullable=True),
    sa.Column('vagas', sa.Integer(), nullable=True),
    sa.Column('status_agendamento', sa.Enum('disponivel', 'reservado', 'cancelado', name='statusagendamento'), nullable=True),
    sa.PrimaryKeyConstraint('oid')
    )
    op.create_index(op.f('ix_Aulas_Disponiveis_oid'), 'Aulas_Disponiveis', ['oid'], unique=False)
    op.create_table('Dados_dos_Alunos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('telefone', sa.String(length=20), nullable=True),
    sa.Column('restricoes', sa.Text(), nullable=True),
    sa.Column('interesses', sa.Text(), nullable=True),
    sa.Column('evolucao', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Dados_dos_Alunos_id'), 'Dados_dos_Alunos', ['id'], unique=False)
    op.create_table('Dashboard',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('total_alunos', sa.Integer(), nullable=True),
    sa.Column('total_professores', sa.Integer(), nullable=True),
    sa.Column('total_estudos', sa.Integer(), nullable=True),
    sa.Column('pagamentos_em_atraso', sa.Integer(), nullable=True),
    sa.Column('alunos_hide', sa.Integer(), nullable=True),
    sa.Column('professores_hide', sa.Integer(), nullable=True),
    sa.Column('ocupacao_media', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Dashboard_id'), 'Dashboard', ['id'], unique=False)
    op.create_table('Gestao_de_Alunos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('telefone', sa.String(length=20), nullable=True),
    sa.Column('endereco', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('ativo', 'inativo', 'pendente', name='status'), nullable=True),
    sa.Column('data_cadastro', sa.Date(), nullable=True),
    sa.Column('total_estudos', sa.Integer(), nullable=True),
    sa.Column('total_professores', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Gestao_de_Alunos_id'), 'Gestao_de_Alunos', ['id'], unique=False)
    op.create_table('Gestao_de_Estudos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=True),
    sa.Column('descricao', sa.String(length=255), nullable=True),
    sa.Column('tipo_estudo', sa.String(length=100), nullable=True),
    sa.Column('status', sa.Enum('ativo', 'inativo', 'pendente', name='status'), nullable=True),
    sa.Column('carga_horaria', sa.Integer(), nullable=True),
    sa.Column('total_professores', sa.Integer(), nullable=True),
    sa.Column('total_alunos', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Gestao_de_Estudos_id'), 'Gestao_de_Estudos', ['id'], unique=False)
    op.create_table('Gestao_de_Professores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('telefone', sa.String(length=20), nullable=True),
    sa.Column('especialidade', sa.String(length=100), nullable=True),
    sa.Column('status', sa.Enum('ativo', 'inativo', 'pendente', name='status'), nullable=True),
    sa.Column('data_cadastro', sa.Date(), nullable=True),
    sa.Column('total_estudos', sa.Integer(), nullable=True),
    sa.Column('total_alunos', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Gestao_de_Professores_id'), 'Gestao_de_Professores', ['id'], unique=False)
    op.create_table('Logs_do_Sistema',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario', sa.String(length=100), nullable=True),
    sa.Column('acao', sa.String(length=100), nullable=True),
    sa.Column('data_hora', sa.DateTime(), nullable=True),
    sa.Column('sistema_operacional', sa.String(length=50), nullable=True),
    sa.Column('navegador', sa.String(length=50), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Logs_do_Sistema_id'), 'Logs_do_Sistema', ['id'], unique=False)
    op.create_table('Meus_Pagamentos',
    sa.Column('oid', sa.Integer(), nullable=False),
    sa.Column('valor', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('data_pagamento', sa.Date(), nullable=False),
    sa.Column('status_pagamento', sa.Enum('pendente', 'pago', 'atrasado', name='statuspagamento'), nullable=True),
    sa.Column('metodo_pagamento', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('oid')
    )
    op.create_index(op.f('ix_Meus_Pagamentos_oid'), 'Meus_Pagamentos', ['oid'], unique=False)
    op.create_table('Minha_Agenda',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data_hora', sa.DateTime(), nullable=False),
    sa.Column('tipo_aula', sa.String(length=50), nullable=True),
    sa.Column('estudo', sa.String(length=100), nullable=True),
    sa.Column('alunos_confirmados', sa.Integer(), nullable=True),
    sa.Column('max_alunos', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('disponivel', 'em_andamento', 'finalizada', name='statusaula'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Minha_Agenda_id'), 'Minha_Agenda', ['id'], unique=False)
    op.create_table('Minha_Conta',
    sa.Column('oid', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=50), nullable=False),
    sa.Column('telefone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('status_pagamento', sa.Enum('pendente', 'pago', 'atrasado', name='statuspagamento'), nullable=True),
    sa.PrimaryKeyConstraint('oid'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_Minha_Conta_oid'), 'Minha_Conta', ['oid'], unique=False)
    op.create_table('Minha_Conta_Professor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('senha', sa.String(length=100), nullable=False),
    sa.Column('identificador', sa.String(length=100), nullable=True),
    sa.Column('tipo_identificador', sa.Enum('cpf', 'rg', 'outro', name='tipoidentificador'), nullable=True),
    sa.Column('professor', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_Minha_Conta_Professor_id'), 'Minha_Conta_Professor', ['id'], unique=False)
    op.create_table('Minha_Evolucao',
    sa.Column('oid', sa.Integer(), nullable=False),
    sa.Column('data_aula', sa.Date(), nullable=False),
    sa.Column('professor', sa.String(length=100), nullable=True),
    sa.Column('exercicios_realizados', sa.Text(), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('progresso', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('oid')
    )
    op.create_index(op.f('ix_Minha_Evolucao_oid'), 'Minha_Evolucao', ['oid'], unique=False)
    op.create_table('Relatorios_Financeiros',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=50), nullable=True),
    sa.Column('data_criacao', sa.Date(), nullable=True),
    sa.Column('total_alunos', sa.Integer(), nullable=True),
    sa.Column('alunos_pagantes', sa.Integer(), nullable=True),
    sa.Column('alunos_inadimplentes', sa.Integer(), nullable=True),
    sa.Column('taxa_ocupacao', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Relatorios_Financeiros_id'), 'Relatorios_Financeiros', ['id'], unique=False)
    op.create_table('Relatorios_de_Evolucao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=True),
    sa.Column('data_criacao', sa.Date(), nullable=True),
    sa.Column('total_estudos', sa.Integer(), nullable=True),
    sa.Column('total_professores', sa.Integer(), nullable=True),
    sa.Column('total_alunos', sa.Integer(), nullable=True),
    sa.Column('alunos_ativos', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Relatorios_de_Evolucao_id'), 'Relatorios_de_Evolucao', ['id'], unique=False)
    op.drop_index('ix_Meus_Pagamentos_oid', table_name='meus_pagamentos')
    op.drop_table('meus_pagamentos')
    op.drop_index('ix_Logs_do_Sistema_id', table_name='logs_do_sistema')
    op.drop_table('logs_do_sistema')
    op.drop_index('ix_Dashboard_id', table_name='dashboard')
    op.drop_table('dashboard')
    op.drop_index('ix_Minha_Agenda_id', table_name='minha_agenda')
    op.drop_table('minha_agenda')
    op.drop_index('email', table_name='minha_conta_professor')
    op.drop_index('ix_Minha_Conta_Professor_id', table_name='minha_conta_professor')
    op.drop_table('minha_conta_professor')
    op.drop_index('ix_Gestao_de_Alunos_id', table_name='gestao_de_alunos')
    op.drop_table('gestao_de_alunos')
    op.drop_index('ix_Gestao_de_Estudos_id', table_name='gestao_de_estudos')
    op.drop_table('gestao_de_estudos')
    op.drop_index('ix_Relatorios_de_Evolucao_id', table_name='relatorios_de_evolucao')
    op.drop_table('relatorios_de_evolucao')
    op.drop_index('ix_Agendamentos_oid', table_name='agendamentos')
    op.drop_table('agendamentos')
    op.drop_index('email', table_name='minha_conta')
    op.drop_index('ix_Minha_Conta_oid', table_name='minha_conta')
    op.drop_table('minha_conta')
    op.drop_index('ix_Gestao_de_Professores_id', table_name='gestao_de_professores')
    op.drop_table('gestao_de_professores')
    op.drop_index('ix_Aulas_Disponiveis_oid', table_name='aulas_disponiveis')
    op.drop_table('aulas_disponiveis')
    op.drop_index('ix_Relatorios_Financeiros_id', table_name='relatorios_financeiros')
    op.drop_table('relatorios_financeiros')
    op.drop_index('ix_Dados_dos_Alunos_id', table_name='dados_dos_alunos')
    op.drop_table('dados_dos_alunos')
    op.drop_table('alunos_na_aula')
    op.drop_index('ix_Minha_Evolucao_oid', table_name='minha_evolucao')
    op.drop_table('minha_evolucao')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('minha_evolucao',
    sa.Column('oid', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('data_aula', sa.DATE(), nullable=False),
    sa.Column('professor', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('exercicios_realizados', mysql.TEXT(), nullable=True),
    sa.Column('observacoes', mysql.TEXT(), nullable=True),
    sa.Column('progresso', mysql.VARCHAR(length=50), nullable=True),
    sa.PrimaryKeyConstraint('oid'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_Minha_Evolucao_oid', 'minha_evolucao', ['oid'], unique=False)
    op.create_table('alunos_na_aula',
    sa.Column('agendamento_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('aula_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('aluno_nome', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('presenca', mysql.ENUM('presente', 'ausente', 'indefinido'), nullable=True),
    sa.Column('observacoes', mysql.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('agendamento_id', 'aula_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('dados_dos_alunos',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nome', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('telefone', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('restricoes', mysql.TEXT(), nullable=True),
    sa.Column('interesses', mysql.TEXT(), nullable=True),
    sa.Column('evolucao', mysql.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_Dados_dos_Alunos_id', 'dados_dos_alunos', ['id'], unique=False)
    op.create_table('relatorios_financeiros',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nome', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('data_criacao', sa.DATE(), nullable=True),
    sa.Column('total_alunos', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('alunos_pagantes', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('alunos_inadimplentes', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('taxa_ocupacao', mysql.DECIMAL(precision=5, scale=2), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_Relatorios_Financeiros_id', 'relatorios_financeiros', ['id'], unique=False)
    op.create_table('aulas_disponiveis',
    sa.Column('oid', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('data_hora', mysql.DATETIME(), nullable=False),
    sa.Column('professor', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('vagas', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('status_agendamento', mysql.ENUM('disponivel', 'reservado', 'cancelado'), nullable=True),
    sa.PrimaryKeyConstraint('oid'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_Aulas_Disponiveis_oid', 'aulas_disponiveis', ['oid'], unique=False)
    op.create_table('gestao_de_professores',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nome', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('email', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('telefone', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('especialidade', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('status', mysql.ENUM('ativo', 'inativo', 'pendente'), nullable=True),
    sa.Column('data_cadastro', sa.DATE(), nullable=True),
    sa.Column('total_estudos', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('total_alunos', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_Gestao_de_Professores_id', 'gestao_de_professores', ['id'], unique=False)
    op.create_table('minha_conta',
    sa.Column('oid', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nome', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('telefone', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('email', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('status_pagamento', mysql.ENUM('pendente', 'pago', 'atrasado'), nullable=True),
    sa.PrimaryKeyConstraint('oid'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_Minha_Conta_oid', 'minha_conta', ['oid'], unique=False)
    op.create_index('email', 'minha_conta', ['email'], unique=True)
    op.create_table('agendamentos',
    sa.Column('oid', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('data_hora', mysql.DATETIME(), nullable=False),
    sa.Column('professor', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('aula', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('minha_presenca', mysql.ENUM('presente', 'ausente', 'indefinido'), nullable=True),
    sa.PrimaryKeyConstraint('oid'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_Agendamentos_oid', 'agendamentos', ['oid'], unique=False)
    op.create_table('relatorios_de_evolucao',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nome', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('data_criacao', sa.DATE(), nullable=True),
    sa.Column('total_estudos', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('total_professores', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('total_alunos', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('alunos_ativos', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_Relatorios_de_Evolucao_id', 'relatorios_de_evolucao', ['id'], unique=False)
    op.create_table('gestao_de_estudos',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nome', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('descricao', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('tipo_estudo', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('status', mysql.ENUM('ativo', 'inativo', 'pendente'), nullable=True),
    sa.Column('carga_horaria', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('total_professores', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('total_alunos', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_Gestao_de_Estudos_id', 'gestao_de_estudos', ['id'], unique=False)
    op.create_table('gestao_de_alunos',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nome', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('email', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('telefone', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('endereco', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('status', mysql.ENUM('ativo', 'inativo', 'pendente'), nullable=True),
    sa.Column('data_cadastro', sa.DATE(), nullable=True),
    sa.Column('total_estudos', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('total_professores', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_Gestao_de_Alunos_id', 'gestao_de_alunos', ['id'], unique=False)
    op.create_table('minha_conta_professor',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nome', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('email', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('senha', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('identificador', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('tipo_identificador', mysql.ENUM('cpf', 'rg', 'outro'), nullable=True),
    sa.Column('professor', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_Minha_Conta_Professor_id', 'minha_conta_professor', ['id'], unique=False)
    op.create_index('email', 'minha_conta_professor', ['email'], unique=True)
    op.create_table('minha_agenda',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('data_hora', mysql.DATETIME(), nullable=False),
    sa.Column('tipo_aula', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('estudo', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('alunos_confirmados', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('max_alunos', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('status', mysql.ENUM('disponivel', 'em_andamento', 'finalizada'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_Minha_Agenda_id', 'minha_agenda', ['id'], unique=False)
    op.create_table('dashboard',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('total_alunos', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('total_professores', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('total_estudos', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('pagamentos_em_atraso', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('alunos_hide', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('professores_hide', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('ocupacao_media', mysql.DECIMAL(precision=5, scale=2), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_Dashboard_id', 'dashboard', ['id'], unique=False)
    op.create_table('logs_do_sistema',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('usuario', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('acao', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('data_hora', mysql.DATETIME(), nullable=True),
    sa.Column('sistema_operacional', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('navegador', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('ip_address', mysql.VARCHAR(length=45), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_Logs_do_Sistema_id', 'logs_do_sistema', ['id'], unique=False)
    op.create_table('meus_pagamentos',
    sa.Column('oid', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('valor', mysql.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('data_pagamento', sa.DATE(), nullable=False),
    sa.Column('status_pagamento', mysql.ENUM('pendente', 'pago', 'atrasado'), nullable=True),
    sa.Column('metodo_pagamento', mysql.VARCHAR(length=50), nullable=True),
    sa.PrimaryKeyConstraint('oid'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_Meus_Pagamentos_oid', 'meus_pagamentos', ['oid'], unique=False)
    op.drop_index(op.f('ix_Relatorios_de_Evolucao_id'), table_name='Relatorios_de_Evolucao')
    op.drop_table('Relatorios_de_Evolucao')
    op.drop_index(op.f('ix_Relatorios_Financeiros_id'), table_name='Relatorios_Financeiros')
    op.drop_table('Relatorios_Financeiros')
    op.drop_index(op.f('ix_Minha_Evolucao_oid'), table_name='Minha_Evolucao')
    op.drop_table('Minha_Evolucao')
    op.drop_index(op.f('ix_Minha_Conta_Professor_id'), table_name='Minha_Conta_Professor')
    op.drop_table('Minha_Conta_Professor')
    op.drop_index(op.f('ix_Minha_Conta_oid'), table_name='Minha_Conta')
    op.drop_table('Minha_Conta')
    op.drop_index(op.f('ix_Minha_Agenda_id'), table_name='Minha_Agenda')
    op.drop_table('Minha_Agenda')
    op.drop_index(op.f('ix_Meus_Pagamentos_oid'), table_name='Meus_Pagamentos')
    op.drop_table('Meus_Pagamentos')
    op.drop_index(op.f('ix_Logs_do_Sistema_id'), table_name='Logs_do_Sistema')
    op.drop_table('Logs_do_Sistema')
    op.drop_index(op.f('ix_Gestao_de_Professores_id'), table_name='Gestao_de_Professores')
    op.drop_table('Gestao_de_Professores')
    op.drop_index(op.f('ix_Gestao_de_Estudos_id'), table_name='Gestao_de_Estudos')
    op.drop_table('Gestao_de_Estudos')
    op.drop_index(op.f('ix_Gestao_de_Alunos_id'), table_name='Gestao_de_Alunos')
    op.drop_table('Gestao_de_Alunos')
    op.drop_index(op.f('ix_Dashboard_id'), table_name='Dashboard')
    op.drop_table('Dashboard')
    op.drop_index(op.f('ix_Dados_dos_Alunos_id'), table_name='Dados_dos_Alunos')
    op.drop_table('Dados_dos_Alunos')
    op.drop_index(op.f('ix_Aulas_Disponiveis_oid'), table_name='Aulas_Disponiveis')
    op.drop_table('Aulas_Disponiveis')
    op.drop_table('Alunos_na_Aula')
    op.drop_index(op.f('ix_Agendamentos_oid'), table_name='Agendamentos')
    op.drop_table('Agendamentos')
    # ### end Alembic commands ###
