"""Revisão das tabelas de alunos E professores

Revision ID: 719704962155
Revises: 83bf65fe0002
Create Date: 2025-10-16 12:45:16.378743

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '719704962155'
down_revision: Union[str, None] = '83bf65fe0002'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alunos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('cpf', sa.String(length=20), nullable=False),
    sa.Column('telefone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('senha', sa.String(length=100), nullable=False),
    sa.Column('data_nascimento', sa.Date(), nullable=True),
    sa.Column('status_pagamento', sa.Enum('pendente', 'pago', 'atrasado', name='status_pagamento_enum'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cpf'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_alunos_id'), 'alunos', ['id'], unique=False)
    op.create_table('aulas_disponiveis',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data_hora', sa.DateTime(), nullable=False),
    sa.Column('professor', sa.String(length=100), nullable=False),
    sa.Column('vagas', sa.Integer(), nullable=False),
    sa.Column('status_agendamento', sa.Enum('disponivel', 'reservado', 'cancelado', name='status_agendamento_enum'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_aulas_disponiveis_id'), 'aulas_disponiveis', ['id'], unique=False)
    op.create_table('dados_dos_alunos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('telefone', sa.String(length=20), nullable=True),
    sa.Column('restricoes', sa.Text(), nullable=True),
    sa.Column('interesses', sa.Text(), nullable=True),
    sa.Column('evolucao', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dados_dos_alunos_id'), 'dados_dos_alunos', ['id'], unique=False)
    op.create_table('professores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('cref', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('senha', sa.String(length=100), nullable=False),
    sa.Column('identificador', sa.String(length=100), nullable=True),
    sa.Column('tipo_identificador', sa.Enum('cpf', 'rg', 'outro', name='tipoidentificador'), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cref'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_professores_id'), 'professores', ['id'], unique=False)
    op.create_table('agendamentos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('aluno_id', sa.Integer(), nullable=False),
    sa.Column('data_hora', sa.DateTime(), nullable=False),
    sa.Column('professor', sa.String(length=100), nullable=False),
    sa.Column('aula', sa.String(length=50), nullable=False),
    sa.Column('minha_presenca', sa.Enum('presente', 'ausente', 'indefinido', name='presenca_enum'), nullable=False),
    sa.ForeignKeyConstraint(['aluno_id'], ['alunos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agendamentos_id'), 'agendamentos', ['id'], unique=False)
    op.create_table('agendas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('professor_id', sa.Integer(), nullable=False),
    sa.Column('data_hora', sa.DateTime(), nullable=False),
    sa.Column('tipo_aula', sa.String(length=50), nullable=True),
    sa.Column('estudo', sa.String(length=100), nullable=True),
    sa.Column('alunos_confirmados', sa.Integer(), nullable=True),
    sa.Column('max_alunos', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('disponivel', 'em_andamento', 'finalizada', name='statusaula'), nullable=True),
    sa.ForeignKeyConstraint(['professor_id'], ['professores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agendas_id'), 'agendas', ['id'], unique=False)
    op.create_table('meus_pagamentos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('aluno_id', sa.Integer(), nullable=False),
    sa.Column('valor', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('data_pagamento', sa.Date(), nullable=False),
    sa.Column('status_pagamento', sa.Enum('pendente', 'pago', 'atrasado', name='status_pagamento_enum'), nullable=False),
    sa.Column('metodo_pagamento', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['aluno_id'], ['alunos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_meus_pagamentos_id'), 'meus_pagamentos', ['id'], unique=False)
    op.create_table('alunos_na_aula',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('agenda_id', sa.Integer(), nullable=False),
    sa.Column('aluno_nome', sa.String(length=100), nullable=True),
    sa.Column('presenca', sa.Enum('presente', 'ausente', 'indefinido', name='presenca'), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['agenda_id'], ['agendas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alunos_na_aula_id'), 'alunos_na_aula', ['id'], unique=False)
    op.create_table('evolucao_alunos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('professor_id', sa.Integer(), nullable=False),
    sa.Column('aluno_id', sa.Integer(), nullable=False),
    sa.Column('agenda_id', sa.Integer(), nullable=False),
    sa.Column('data_aula', sa.DateTime(), nullable=False),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('progresso', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['agenda_id'], ['agendas.id'], ),
    sa.ForeignKeyConstraint(['aluno_id'], ['alunos.id'], ),
    sa.ForeignKeyConstraint(['professor_id'], ['professores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('minha_evolucao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('aluno_id', sa.Integer(), nullable=False),
    sa.Column('professor_id', sa.Integer(), nullable=False),
    sa.Column('agenda_id', sa.Integer(), nullable=False),
    sa.Column('data_aula', sa.DateTime(), nullable=False),
    sa.Column('exercicios_realizados', sa.Text(), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('progresso', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['agenda_id'], ['agendas.id'], ),
    sa.ForeignKeyConstraint(['aluno_id'], ['alunos.id'], ),
    sa.ForeignKeyConstraint(['professor_id'], ['professores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('minha_evolucao')
    op.drop_table('evolucao_alunos')
    op.drop_index(op.f('ix_alunos_na_aula_id'), table_name='alunos_na_aula')
    op.drop_table('alunos_na_aula')
    op.drop_index(op.f('ix_meus_pagamentos_id'), table_name='meus_pagamentos')
    op.drop_table('meus_pagamentos')
    op.drop_index(op.f('ix_agendas_id'), table_name='agendas')
    op.drop_table('agendas')
    op.drop_index(op.f('ix_agendamentos_id'), table_name='agendamentos')
    op.drop_table('agendamentos')
    op.drop_index(op.f('ix_professores_id'), table_name='professores')
    op.drop_table('professores')
    op.drop_index(op.f('ix_dados_dos_alunos_id'), table_name='dados_dos_alunos')
    op.drop_table('dados_dos_alunos')
    op.drop_index(op.f('ix_aulas_disponiveis_id'), table_name='aulas_disponiveis')
    op.drop_table('aulas_disponiveis')
    op.drop_index(op.f('ix_alunos_id'), table_name='alunos')
    op.drop_table('alunos')
    # ### end Alembic commands ###
