"""Revisão das tabelas de  admin

Revision ID: 83bf65fe0002
Revises: 00dc78ac70bb
Create Date: 2025-10-16 12:11:35.180420

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '83bf65fe0002'
down_revision: Union[str, None] = '00dc78ac70bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('senha', sa.String(length=100), nullable=False),
    sa.Column('tipo_admin', sa.Enum('admin_completo', 'recepcionista', 'financeiro', name='tipoadmin'), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_admins_id'), 'admins', ['id'], unique=False)
    op.create_table('dashboards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('total_alunos', sa.Integer(), nullable=True),
    sa.Column('total_professores', sa.Integer(), nullable=True),
    sa.Column('total_estudos', sa.Integer(), nullable=True),
    sa.Column('pagamentos_em_atraso', sa.Integer(), nullable=True),
    sa.Column('alunos_hide', sa.Integer(), nullable=True),
    sa.Column('professores_hide', sa.Integer(), nullable=True),
    sa.Column('ocupacao_media', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dashboards_id'), 'dashboards', ['id'], unique=False)
    op.create_table('gestao_de_alunos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('telefone', sa.String(length=20), nullable=True),
    sa.Column('endereco', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('ativo', 'inativo', 'pendente', name='status'), nullable=True),
    sa.Column('data_cadastro', sa.Date(), nullable=True),
    sa.Column('total_estudos', sa.Integer(), nullable=True),
    sa.Column('total_professores', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gestao_de_alunos_id'), 'gestao_de_alunos', ['id'], unique=False)
    op.create_table('gestao_de_estudios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=True),
    sa.Column('descricao', sa.String(length=255), nullable=True),
    sa.Column('tipo_estudo', sa.String(length=100), nullable=True),
    sa.Column('status', sa.Enum('ativo', 'inativo', 'pendente', name='status'), nullable=True),
    sa.Column('carga_horaria', sa.Integer(), nullable=True),
    sa.Column('total_professores', sa.Integer(), nullable=True),
    sa.Column('total_alunos', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gestao_de_estudios_id'), 'gestao_de_estudios', ['id'], unique=False)
    op.create_table('gestao_de_professores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('telefone', sa.String(length=20), nullable=True),
    sa.Column('especialidade', sa.String(length=100), nullable=True),
    sa.Column('status', sa.Enum('ativo', 'inativo', 'pendente', name='status'), nullable=True),
    sa.Column('data_cadastro', sa.Date(), nullable=True),
    sa.Column('total_estudos', sa.Integer(), nullable=True),
    sa.Column('total_alunos', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gestao_de_professores_id'), 'gestao_de_professores', ['id'], unique=False)
    op.create_table('relatorios_de_evolucao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=True),
    sa.Column('data_criacao', sa.Date(), nullable=True),
    sa.Column('total_estudos', sa.Integer(), nullable=True),
    sa.Column('total_professores', sa.Integer(), nullable=True),
    sa.Column('total_alunos', sa.Integer(), nullable=True),
    sa.Column('alunos_ativos', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_relatorios_de_evolucao_id'), 'relatorios_de_evolucao', ['id'], unique=False)
    op.create_table('relatorios_financeiros',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=50), nullable=True),
    sa.Column('data_criacao', sa.Date(), nullable=True),
    sa.Column('total_alunos', sa.Integer(), nullable=True),
    sa.Column('alunos_pagantes', sa.Integer(), nullable=True),
    sa.Column('alunos_inadimplentes', sa.Integer(), nullable=True),
    sa.Column('taxa_ocupacao', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_relatorios_financeiros_id'), 'relatorios_financeiros', ['id'], unique=False)
    op.create_table('logs_do_sistema',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('admin_id', sa.Integer(), nullable=False),
    sa.Column('acao', sa.String(length=255), nullable=True),
    sa.Column('data_hora', sa.DateTime(), nullable=True),
    sa.Column('sistema_operacional', sa.String(length=50), nullable=True),
    sa.Column('navegador', sa.String(length=50), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.ForeignKeyConstraint(['admin_id'], ['admins.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_logs_do_sistema_id'), 'logs_do_sistema', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_logs_do_sistema_id'), table_name='logs_do_sistema')
    op.drop_table('logs_do_sistema')
    op.drop_index(op.f('ix_relatorios_financeiros_id'), table_name='relatorios_financeiros')
    op.drop_table('relatorios_financeiros')
    op.drop_index(op.f('ix_relatorios_de_evolucao_id'), table_name='relatorios_de_evolucao')
    op.drop_table('relatorios_de_evolucao')
    op.drop_index(op.f('ix_gestao_de_professores_id'), table_name='gestao_de_professores')
    op.drop_table('gestao_de_professores')
    op.drop_index(op.f('ix_gestao_de_estudios_id'), table_name='gestao_de_estudios')
    op.drop_table('gestao_de_estudios')
    op.drop_index(op.f('ix_gestao_de_alunos_id'), table_name='gestao_de_alunos')
    op.drop_table('gestao_de_alunos')
    op.drop_index(op.f('ix_dashboards_id'), table_name='dashboards')
    op.drop_table('dashboards')
    op.drop_index(op.f('ix_admins_id'), table_name='admins')
    op.drop_table('admins')
    # ### end Alembic commands ###
