"""Criando as tabelas do aluno

Revision ID: 95e83869bb7c
Revises: 8aa5fc838372
Create Date: 2025-10-09 01:55:03.096080

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '95e83869bb7c'
down_revision: Union[str, None] = '8aa5fc838372'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Agendamentos',
    sa.Column('oid', sa.Integer(), nullable=False),
    sa.Column('data_hora', sa.DateTime(), nullable=False),
    sa.Column('professor', sa.String(length=100), nullable=True),
    sa.Column('aula', sa.String(length=50), nullable=True),
    sa.Column('minha_presenca', sa.Enum('presente', 'ausente', 'indefinido', name='presenca'), nullable=True),
    sa.PrimaryKeyConstraint('oid')
    )
    op.create_index(op.f('ix_Agendamentos_oid'), 'Agendamentos', ['oid'], unique=False)
    op.create_table('Aulas_Disponiveis',
    sa.Column('oid', sa.Integer(), nullable=False),
    sa.Column('data_hora', sa.DateTime(), nullable=False),
    sa.Column('professor', sa.String(length=100), nullable=True),
    sa.Column('vagas', sa.Integer(), nullable=True),
    sa.Column('status_agendamento', sa.Enum('disponivel', 'reservado', 'cancelado', name='statusagendamento'), nullable=True),
    sa.PrimaryKeyConstraint('oid')
    )
    op.create_index(op.f('ix_Aulas_Disponiveis_oid'), 'Aulas_Disponiveis', ['oid'], unique=False)
    op.create_table('Meus_Pagamentos',
    sa.Column('oid', sa.Integer(), nullable=False),
    sa.Column('valor', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('data_pagamento', sa.Date(), nullable=False),
    sa.Column('status_pagamento', sa.Enum('pendente', 'pago', 'atrasado', name='statuspagamento'), nullable=True),
    sa.Column('metodo_pagamento', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('oid')
    )
    op.create_index(op.f('ix_Meus_Pagamentos_oid'), 'Meus_Pagamentos', ['oid'], unique=False)
    op.create_table('Minha_Conta',
    sa.Column('oid', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=50), nullable=False),
    sa.Column('telefone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('status_pagamento', sa.Enum('pendente', 'pago', 'atrasado', name='statuspagamento'), nullable=True),
    sa.PrimaryKeyConstraint('oid'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_Minha_Conta_oid'), 'Minha_Conta', ['oid'], unique=False)
    op.create_table('Minha_Evolucao',
    sa.Column('oid', sa.Integer(), nullable=False),
    sa.Column('data_aula', sa.Date(), nullable=False),
    sa.Column('professor', sa.String(length=100), nullable=True),
    sa.Column('exercicios_realizados', sa.Text(), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('progresso', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('oid')
    )
    op.create_index(op.f('ix_Minha_Evolucao_oid'), 'Minha_Evolucao', ['oid'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_Minha_Evolucao_oid'), table_name='Minha_Evolucao')
    op.drop_table('Minha_Evolucao')
    op.drop_index(op.f('ix_Minha_Conta_oid'), table_name='Minha_Conta')
    op.drop_table('Minha_Conta')
    op.drop_index(op.f('ix_Meus_Pagamentos_oid'), table_name='Meus_Pagamentos')
    op.drop_table('Meus_Pagamentos')
    op.drop_index(op.f('ix_Aulas_Disponiveis_oid'), table_name='Aulas_Disponiveis')
    op.drop_table('Aulas_Disponiveis')
    op.drop_index(op.f('ix_Agendamentos_oid'), table_name='Agendamentos')
    op.drop_table('Agendamentos')
    # ### end Alembic commands ###
