"""Revisão das tabelas 

Revision ID: ba588044ed5a
Revises: 719704962155
Create Date: 2025-10-16 13:26:17.721576

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ba588044ed5a'
down_revision: Union[str, None] = '719704962155'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('senha', sa.String(length=100), nullable=False),
    sa.Column('tipo_admin', sa.Enum('admin_completo', 'recepcionista', 'financeiro', name='tipoadmin'), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_admins_id'), 'admins', ['id'], unique=False)
    op.create_table('alunos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('cpf', sa.String(length=20), nullable=False),
    sa.Column('telefone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('senha', sa.String(length=100), nullable=False),
    sa.Column('data_nascimento', sa.Date(), nullable=True),
    sa.Column('status_pagamento', sa.Enum('pendente', 'pago', 'atrasado', name='status_pagamento_enum'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cpf'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_alunos_id'), 'alunos', ['id'], unique=False)
    op.create_table('dashboards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('total_alunos', sa.Integer(), nullable=True),
    sa.Column('total_professores', sa.Integer(), nullable=True),
    sa.Column('total_estudos', sa.Integer(), nullable=True),
    sa.Column('pagamentos_em_atraso', sa.Integer(), nullable=True),
    sa.Column('ocupacao_media', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dashboards_id'), 'dashboards', ['id'], unique=False)
    op.create_table('professores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('cref', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('senha', sa.String(length=100), nullable=False),
    sa.Column('identificador', sa.String(length=100), nullable=True),
    sa.Column('tipo_identificador', sa.Enum('cpf', 'rg', 'outro', name='tipoidentificador'), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cref'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_professores_id'), 'professores', ['id'], unique=False)
    op.create_table('agendas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('professor_id', sa.Integer(), nullable=False),
    sa.Column('data_hora', sa.DateTime(), nullable=False),
    sa.Column('tipo_aula', sa.String(length=50), nullable=True),
    sa.Column('estudo', sa.String(length=100), nullable=True),
    sa.Column('alunos_confirmados', sa.Integer(), nullable=True),
    sa.Column('max_alunos', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('disponivel', 'em_andamento', 'finalizada', name='statusaula'), nullable=True),
    sa.ForeignKeyConstraint(['professor_id'], ['professores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agendas_id'), 'agendas', ['id'], unique=False)
    op.create_table('logs_do_sistema',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('admin_id', sa.Integer(), nullable=False),
    sa.Column('acao', sa.String(length=255), nullable=True),
    sa.Column('data_hora', sa.DateTime(), nullable=True),
    sa.Column('sistema_operacional', sa.String(length=50), nullable=True),
    sa.Column('navegador', sa.String(length=50), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.ForeignKeyConstraint(['admin_id'], ['admins.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_logs_do_sistema_id'), 'logs_do_sistema', ['id'], unique=False)
    op.create_table('meus_pagamentos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('aluno_id', sa.Integer(), nullable=False),
    sa.Column('valor', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('data_pagamento', sa.Date(), nullable=False),
    sa.Column('status_pagamento', sa.Enum('pendente', 'pago', 'atrasado', name='status_pagamento_enum'), nullable=False),
    sa.Column('metodo_pagamento', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['aluno_id'], ['alunos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_meus_pagamentos_id'), 'meus_pagamentos', ['id'], unique=False)
    op.create_table('agendamentos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('aluno_id', sa.Integer(), nullable=False),
    sa.Column('professor_id', sa.Integer(), nullable=False),
    sa.Column('aula_id', sa.Integer(), nullable=False),
    sa.Column('data_hora', sa.DateTime(), nullable=False),
    sa.Column('minha_presenca', sa.Enum('presente', 'ausente', 'indefinido', name='presenca_enum'), nullable=False),
    sa.ForeignKeyConstraint(['aluno_id'], ['alunos.id'], ),
    sa.ForeignKeyConstraint(['aula_id'], ['agendas.id'], ),
    sa.ForeignKeyConstraint(['professor_id'], ['professores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agendamentos_id'), 'agendamentos', ['id'], unique=False)
    op.create_table('alunos_na_aula',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('agenda_id', sa.Integer(), nullable=False),
    sa.Column('aluno_id', sa.Integer(), nullable=False),
    sa.Column('presenca', sa.Enum('presente', 'ausente', 'indefinido', name='presenca'), nullable=True),
    sa.Column('observacoes', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['agenda_id'], ['agendas.id'], ),
    sa.ForeignKeyConstraint(['aluno_id'], ['alunos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alunos_na_aula_id'), 'alunos_na_aula', ['id'], unique=False)
    op.create_table('minha_evolucao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('aluno_id', sa.Integer(), nullable=False),
    sa.Column('professor_id', sa.Integer(), nullable=False),
    sa.Column('agenda_id', sa.Integer(), nullable=False),
    sa.Column('data_aula', sa.DateTime(), nullable=False),
    sa.Column('exercicios_realizados', sa.Text(), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('progresso', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['agenda_id'], ['agendas.id'], ),
    sa.ForeignKeyConstraint(['aluno_id'], ['alunos.id'], ),
    sa.ForeignKeyConstraint(['professor_id'], ['professores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('minha_evolucao')
    op.drop_index(op.f('ix_alunos_na_aula_id'), table_name='alunos_na_aula')
    op.drop_table('alunos_na_aula')
    op.drop_index(op.f('ix_agendamentos_id'), table_name='agendamentos')
    op.drop_table('agendamentos')
    op.drop_index(op.f('ix_meus_pagamentos_id'), table_name='meus_pagamentos')
    op.drop_table('meus_pagamentos')
    op.drop_index(op.f('ix_logs_do_sistema_id'), table_name='logs_do_sistema')
    op.drop_table('logs_do_sistema')
    op.drop_index(op.f('ix_agendas_id'), table_name='agendas')
    op.drop_table('agendas')
    op.drop_index(op.f('ix_professores_id'), table_name='professores')
    op.drop_table('professores')
    op.drop_index(op.f('ix_dashboards_id'), table_name='dashboards')
    op.drop_table('dashboards')
    op.drop_index(op.f('ix_alunos_id'), table_name='alunos')
    op.drop_table('alunos')
    op.drop_index(op.f('ix_admins_id'), table_name='admins')
    op.drop_table('admins')
    # ### end Alembic commands ###
