"""Add estudio and update professor relations

Revision ID: ccee643bc5f0
Revises: ba588044ed5a
Create Date: 2025-10-17 12:08:03.060788

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ccee643bc5f0'
down_revision: Union[str, None] = 'ba588044ed5a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('estudios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('endereco', sa.String(length=255), nullable=False),
    sa.Column('cep', sa.String(length=9), nullable=False),
    sa.Column('telefone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('capacidade_maxima', sa.Integer(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_estudios_id'), 'estudios', ['id'], unique=False)
    op.add_column('agendas', sa.Column('estudio_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'agendas', 'estudios', ['estudio_id'], ['id'])
    op.add_column('professores', sa.Column('estudio_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'professores', 'estudios', ['estudio_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'professores', type_='foreignkey')
    op.drop_column('professores', 'estudio_id')
    op.drop_constraint(None, 'agendas', type_='foreignkey')
    op.drop_column('agendas', 'estudio_id')
    op.drop_index(op.f('ix_estudios_id'), table_name='estudios')
    op.drop_table('estudios')
    # ### end Alembic commands ###
